[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
PYTHONPATH = "/app"

